run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - goconst
    - gocritic
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - scopelint
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

issues:
  exclude:
    # https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope .* in function literal

linters-settings:
  goimports:
    local-prefixes: github.com/david7482/lambda-extension-log-shipper