name: commit

on:
  workflow_dispatch: # Manually run this workflow
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        run: make lint